import re
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

from models import AnalysisResult

REPORTS_DIR = Path(__file__).parent / "data" / "reports"

# Unicode -> ASCII replacements for Helvetica compatibility
_UNICODE_MAP = {
    "\u2014": "-",   # em-dash
    "\u2013": "-",   # en-dash
    "\u2018": "'",   # left single quote
    "\u2019": "'",   # right single quote
    "\u201c": '"',   # left double quote
    "\u201d": '"',   # right double quote
    "\u2026": "...", # ellipsis
    "\u2022": "-",   # bullet
    "\u2032": "'",   # prime
    "\u2033": '"',   # double prime
    "\u00a0": " ",   # non-breaking space
    "\u200b": "",    # zero-width space
    "\u2010": "-",   # hyphen
    "\u2011": "-",   # non-breaking hyphen
    "\u2012": "-",   # figure dash
    "\u2015": "-",   # horizontal bar
    "\u2212": "-",   # minus sign
    "\u2264": "<=",  # less than or equal
    "\u2265": ">=",  # greater than or equal
    "\ufb01": "fi",  # fi ligature
    "\ufb02": "fl",  # fl ligature
}


def _sanitize(text: str) -> str:
    """Replace Unicode characters unsupported by Helvetica with ASCII."""
    for uc, asc in _UNICODE_MAP.items():
        text = text.replace(uc, asc)
    # Remove any remaining non-latin1 characters
    return text.encode("latin-1", errors="replace").decode("latin-1")


class ReportPDF(FPDF):
    def __init__(self, symbol: str, company_name: str):
        super().__init__()
        self.symbol = symbol
        self.company_name = company_name
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 8, f"{self.symbol} | {self.company_name}", align="L")
        self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(160, 160, 160)
        self.cell(
            0, 10,
            "Generated by CSE Investment Analyzer | Not regulated investment advice",
            align="C",
        )


def generate_report(result: AnalysisResult) -> Path:
    """Generate a PDF report from the analysis result."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    date_str = result.generated_at.strftime("%Y%m%d")
    output_path = REPORTS_DIR / f"{result.symbol}_analysis_{date_str}.pdf"

    pdf = ReportPDF(result.symbol, result.company_name)

    # Title page
    _add_title_page(pdf, result)

    # Body
    pdf.add_page()
    _render_markdown(pdf, result.analysis_text)

    pdf.output(str(output_path))
    print(f"  Report saved: {output_path}")
    return output_path


def _add_title_page(pdf: ReportPDF, result: AnalysisResult):
    pdf.add_page()
    pdf.ln(50)

    # Company name
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(20, 40, 80)
    pdf.cell(0, 15, _sanitize(result.company_name), align="C", new_x="LMARGIN", new_y="NEXT")

    # Symbol
    pdf.set_font("Helvetica", "", 20)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 12, f"({result.symbol})", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)

    # Line
    pdf.set_draw_color(20, 40, 80)
    pdf.set_line_width(0.8)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(10)

    # Report title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 10, "Investment Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")

    # Period
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, _sanitize(result.period), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(20)

    # Date
    pdf.set_font("Helvetica", "", 11)
    date_text = result.generated_at.strftime("Generated: %d %B %Y")
    pdf.cell(0, 8, date_text, align="C", new_x="LMARGIN", new_y="NEXT")

    # Source
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.ln(5)
    pdf.cell(0, 8, "Data source: Colombo Stock Exchange (cse.lk)", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, "Analysis powered by Claude AI", align="C", new_x="LMARGIN", new_y="NEXT")


def _render_markdown(pdf: ReportPDF, text: str):
    """Render markdown-formatted text into the PDF."""
    text = _sanitize(text)
    lines = text.split("\n")
    in_table = False
    table_rows: list[list[str]] = []

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Skip empty lines
        if not stripped:
            if in_table and table_rows:
                _render_table(pdf, table_rows)
                table_rows = []
                in_table = False
            pdf.ln(2)
            i += 1
            continue

        # Table row
        if "|" in stripped and stripped.startswith("|"):
            # Skip separator rows like |---|---|
            if re.match(r"^\|[\s\-:|]+\|$", stripped):
                i += 1
                continue
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            table_rows.append(cells)
            in_table = True
            i += 1
            continue

        # Flush any pending table
        if in_table and table_rows:
            _render_table(pdf, table_rows)
            table_rows = []
            in_table = False

        # H1
        if stripped.startswith("# ") and not stripped.startswith("## "):
            pdf.ln(6)
            pdf.set_font("Helvetica", "B", 18)
            pdf.set_text_color(20, 40, 80)
            pdf.multi_cell(0, 9, stripped[2:])
            pdf.ln(3)
            i += 1
            continue

        # H2
        if stripped.startswith("## "):
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(20, 50, 100)
            pdf.multi_cell(0, 8, stripped[3:])
            # Underline
            y = pdf.get_y()
            pdf.set_draw_color(20, 50, 100)
            pdf.set_line_width(0.4)
            pdf.line(10, y, 200, y)
            pdf.ln(3)
            i += 1
            continue

        # H3
        if stripped.startswith("### "):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 7, stripped[4:])
            pdf.ln(2)
            i += 1
            continue

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            pdf.ln(3)
            pdf.set_draw_color(180, 180, 180)
            pdf.set_line_width(0.3)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
            i += 1
            continue

        # Bullet point
        if stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
            content = stripped[2:]
            content = _render_inline_formatting(content)
            pdf.set_x(15)
            pdf.cell(5, 6, "-")
            pdf.multi_cell(170, 6, content)
            i += 1
            continue

        # Numbered list
        num_match = re.match(r"^(\d+)\.\s+(.+)", stripped)
        if num_match:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
            num = num_match.group(1)
            content = num_match.group(2)
            content = _render_inline_formatting(content)
            pdf.set_x(15)
            pdf.cell(8, 6, f"{num}.")
            pdf.multi_cell(167, 6, content)
            i += 1
            continue

        # Regular paragraph
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        pdf.set_x(pdf.l_margin)
        text_content = _render_inline_formatting(stripped)
        pdf.multi_cell(0, 6, text_content)
        i += 1

    # Flush final table
    if in_table and table_rows:
        _render_table(pdf, table_rows)


def _render_inline_formatting(text: str) -> str:
    """Strip markdown inline formatting (bold, italic) for plain text rendering."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    return text


def _render_table(pdf: ReportPDF, rows: list[list[str]]):
    """Render a markdown table in the PDF."""
    if not rows:
        return

    num_cols = max(len(row) for row in rows)
    if num_cols == 0:
        return

    # Calculate column widths based on content
    available_width = 190
    col_widths = _calculate_col_widths(rows, num_cols, available_width, pdf)

    # Check if table fits on current page
    table_height = len(rows) * 7
    if pdf.get_y() + table_height > 270:
        pdf.add_page()

    pdf.set_font("Helvetica", "", 8)

    for row_idx, row in enumerate(rows):
        # Pad row to match column count
        while len(row) < num_cols:
            row.append("")

        # Header row styling
        if row_idx == 0:
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(20, 40, 80)
            pdf.set_text_color(255, 255, 255)
            fill = True
        else:
            pdf.set_font("Helvetica", "", 8)
            if row_idx % 2 == 0:
                pdf.set_fill_color(240, 245, 250)
                fill = True
            else:
                fill = False
            pdf.set_text_color(40, 40, 40)

        max_height = 7
        for col_idx, cell in enumerate(row):
            cell_text = _render_inline_formatting(cell.strip())
            w = col_widths[col_idx]
            # Right-align numeric content
            align = "R" if col_idx > 0 and _is_numeric(cell_text) else "L"
            pdf.cell(w, max_height, cell_text[:50], border=0, fill=fill, align=align)
        pdf.ln(max_height)

    pdf.ln(3)


def _calculate_col_widths(
    rows: list[list[str]], num_cols: int, available: float, pdf: FPDF
) -> list[float]:
    """Calculate proportional column widths."""
    max_lens = [0] * num_cols
    for row in rows:
        for i, cell in enumerate(row):
            if i < num_cols:
                max_lens[i] = max(max_lens[i], len(cell.strip()))

    total = sum(max_lens) or 1
    widths = [(l / total) * available for l in max_lens]

    # Enforce minimum width
    min_w = 15
    for i in range(num_cols):
        if widths[i] < min_w:
            widths[i] = min_w

    # Normalize to fit available width
    total_w = sum(widths)
    if total_w > available:
        factor = available / total_w
        widths = [w * factor for w in widths]

    return widths


def _is_numeric(text: str) -> bool:
    """Check if text looks like a number."""
    cleaned = text.replace(",", "").replace("%", "").replace("(", "").replace(")", "").replace("-", "").strip()
    if not cleaned:
        return False
    try:
        float(cleaned)
        return True
    except ValueError:
        return "." in cleaned and cleaned.replace(".", "").isdigit()
